import 'package:flutter/material.dart';
import 'coupon.dart';
import 'offer.dart';
import 'product.dart';
import 'review.dart';

/// In-memory catalog for Sprint 1.8. Sprint 2 replaces these lists with the
/// backend API via `MarketplaceRepository` — the UI never reads these directly.
const List<Category> kMarketplaceCategories = [
  Category(id: 'engine-parts', name: 'Engine Parts', icon: Icons.settings_rounded),
  Category(id: 'brake-system', name: 'Brake System', icon: Icons.disc_full_rounded),
  Category(id: 'oils', name: 'Oils', icon: Icons.oil_barrel_rounded),
  Category(id: 'tyres', name: 'Tyres', icon: Icons.speed_rounded),
  Category(id: 'batteries', name: 'Batteries', icon: Icons.battery_charging_full_rounded),
  Category(id: 'accessories', name: 'Accessories', icon: Icons.backpack_rounded),
  Category(id: 'cleaning', name: 'Cleaning', icon: Icons.cleaning_services_rounded),
  Category(id: 'lights', name: 'Lights', icon: Icons.lightbulb_rounded),
  Category(id: 'filters', name: 'Filters', icon: Icons.filter_alt_rounded),
  Category(id: 'electronics', name: 'Electronics', icon: Icons.electrical_services_rounded),
];

const List<Brand> kMarketplaceBrands = [
  Brand(id: 'bosch', name: 'Bosch'),
  Brand(id: 'tvs', name: 'TVS'),
  Brand(id: 'rolon', name: 'Rolon'),
  Brand(id: 'ngk', name: 'NGK'),
  Brand(id: 'hero', name: 'Hero'),
  Brand(id: 'castrol', name: 'Castrol'),
  Brand(id: 'motul', name: 'Motul'),
  Brand(id: 'mrf', name: 'MRF'),
  Brand(id: 'ceat', name: 'CEAT'),
  Brand(id: 'exide', name: 'Exide'),
  Brand(id: 'amaron', name: 'Amaron'),
  Brand(id: '3m', name: '3M'),
  Brand(id: 'philips', name: 'Philips'),
  Brand(id: 'hella', name: 'Hella'),
  Brand(id: 'osram', name: 'Osram'),
];

final List<Offer> kMarketplaceOffers = [
  const Offer(
    id: 'offer-brake',
    title: 'Brake & Filter Mega Sale',
    subtitle: 'Up to 40% off on braking and filtration parts',
    code: 'MECHA40',
    gradientStart: Color(0xFFF15A22),
    gradientEnd: Color(0xFFD44A15),
    categoryId: 'brake-system',
  ),
  const Offer(
    id: 'offer-tyre',
    title: 'Tyre Week',
    subtitle: 'Free fitting on all tyres this weekend',
    code: 'TYRE20',
    gradientStart: Color(0xFF4285F4),
    gradientEnd: Color(0xFF1565C0),
    categoryId: 'tyres',
  ),
  const Offer(
    id: 'offer-oil',
    title: 'Engine Care',
    subtitle: 'Oils & lubes starting at ₹349',
    code: 'OIL25',
    gradientStart: Color(0xFF10B981),
    gradientEnd: Color(0xFF065F46),
    categoryId: 'oils',
  ),
];

const List<Coupon> kMarketplaceCoupons = [
  Coupon(
    id: 'coupon-mecha10',
    code: 'MECHA10',
    title: '10% off up to ₹500',
    description: 'Valid on orders above ₹499',
    type: CouponType.percent,
    value: 10,
    maxDiscount: 500,
    minOrderValue: 499,
  ),
  Coupon(
    id: 'coupon-mecha20',
    code: 'MECHA20',
    title: '20% off up to ₹1,000',
    description: 'Valid on orders above ₹1,499',
    type: CouponType.percent,
    value: 20,
    maxDiscount: 1000,
    minOrderValue: 1499,
  ),
  Coupon(
    id: 'coupon-freeship',
    code: 'FREESHIP',
    title: 'Free delivery',
    description: 'Free delivery on any order',
    type: CouponType.freeDelivery,
  ),
];

Review _rv(
  String id,
  String author,
  double rating,
  String comment,
  String date, {
  bool verified = true,
  int helpful = 0,
  List<String> photos = const [],
}) =>
    Review(
      id: id,
      author: author,
      rating: rating,
      comment: comment,
      date: date,
      isVerifiedPurchase: verified,
      helpfulCount: helpful,
      photoUrls: photos,
    );

Product _p(
  String id,
  String name,
  String brandId,
  String brand,
  String categoryId,
  double price,
  double mrp, {
  double rating = 4.0,
  int ratingCount = 120,
  int stock = 25,
  String? image,
  IconData icon = Icons.inventory_2_rounded,
  String description = '',
  List<ProductSpecification> specifications = const [],
  List<VehicleType> vehicles = const [VehicleType.bike, VehicleType.car],
  List<String> compatibility = const [],
  String warranty = '6 months brand warranty',
  String deliveryEstimate = 'Delivery in 3-5 days',
  int popularity = 50,
  int ageDays = 60,
  bool featured = false,
  bool bestSeller = false,
  bool trending = false,
  bool flashDeal = false,
  bool recommended = true,
  List<Review> reviews = const [],
}) =>
    Product(
      id: id,
      name: name,
      brand: brand,
      brandId: brandId,
      categoryId: categoryId,
      price: price,
      mrp: mrp,
      rating: rating,
      ratingCount: ratingCount,
      stock: stock,
      imageUrl: image,
      icon: icon,
      description: description,
      specifications: specifications,
      vehicleTypes: vehicles,
      compatibility: compatibility,
      warranty: warranty,
      deliveryEstimate: deliveryEstimate,
      popularity: popularity,
      ageDays: ageDays,
      isFeatured: featured,
      isBestSeller: bestSeller,
      isTrending: trending,
      isFlashDeal: flashDeal,
      isRecommended: recommended,
      reviews: reviews,
    );

final List<Product> kMarketplaceProducts = [
  // ── Engine Parts ─────────────────────────────────────────────────────
  _p(
    'p-chain-kit',
    'Rolon Chain Sprocket Kit',
    'rolon',
    'Rolon',
    'engine-parts',
    899,
    1199,
    rating: 4.4,
    ratingCount: 340,
    image: 'assets/chain kit.png',
    description:
        'Heavy-duty Rolon chain sprocket kit with pre-greased O-ring chain for smooth and durable power transfer.',
    specifications: const [
      ProductSpecification(label: 'Type', value: 'Chain Sprocket Kit'),
      ProductSpecification(label: 'Pitch', value: '428'),
      ProductSpecification(label: 'Links', value: '110'),
      ProductSpecification(label: 'Material', value: 'Carbon Steel'),
    ],
    compatibility: const ['Pulsar 150', 'Discover 125', 'Honda CB Shine'],
    popularity: 78,
    ageDays: 12,
    trending: true,
    reviews: [
      _rv('rv-chain-1', 'Ravi Kumar', 5, 'Perfect fit on my Pulsar, very smooth now.', '2 weeks ago', helpful: 12),
      _rv('rv-chain-2', 'Sandeep', 4, 'Good quality kit, slight delay in delivery.', '1 month ago', helpful: 4),
    ],
  ),
  _p(
    'p-spark-plug',
    'NGK Iridium Spark Plug',
    'ngk',
    'NGK',
    'engine-parts',
    549,
    699,
    rating: 4.6,
    ratingCount: 890,
    image: 'assets/spark plugs.png',
    description:
        'NGK iridium-tipped spark plug for better ignition, fuel economy and a cleaner burn across the rev range.',
    specifications: const [
      ProductSpecification(label: 'Type', value: 'Iridium IX'),
      ProductSpecification(label: 'Thread', value: 'M14 x 1.25'),
      ProductSpecification(label: 'Heat Range', value: '7'),
      ProductSpecification(label: 'Gap', value: '0.8 mm'),
    ],
    compatibility: const ['Pulsar', 'Apache', 'FZ', 'Activa'],
    popularity: 92,
    ageDays: 8,
    bestSeller: true,
    trending: true,
    reviews: [
      _rv('rv-plug-1', 'Karthik N', 5, 'Startup improved instantly. Great plug.', '3 weeks ago', helpful: 21),
      _rv('rv-plug-2', 'Priya S', 4, 'Good value, works as advertised.', '1 month ago', verified: false, helpful: 3),
    ],
  ),
  _p(
    'p-clutch-lever',
    'Racing Clutch Lever',
    'tvs',
    'TVS',
    'engine-parts',
    299,
    399,
    rating: 4.1,
    ratingCount: 210,
    image: 'assets/clutch lever.png',
    description: 'CNC-machined aluminium clutch lever with adjustable reach for a sportier feel.',
    specifications: const [
      ProductSpecification(label: 'Material', value: 'Aluminium'),
      ProductSpecification(label: 'Reach', value: 'Adjustable'),
      ProductSpecification(label: 'Colour', value: 'Black / Red'),
    ],
    popularity: 45,
    ageDays: 34,
    reviews: [
      _rv('rv-clutch-1', 'Vishnu', 4, 'Feels premium, easy install.', '2 weeks ago', helpful: 2),
    ],
  ),
  _p(
    'p-radiator',
    'Aluminium Radiator',
    'tvs',
    'TVS',
    'engine-parts',
    2499,
    2999,
    rating: 4.3,
    ratingCount: 96,
    image: 'assets/radiator.png',
    description: 'High-capacity aluminium radiator for improved engine cooling on hot rides.',
    specifications: const [
      ProductSpecification(label: 'Core Material', value: 'Aluminium'),
      ProductSpecification(label: 'Tank', value: 'Plastic / Aluminium'),
      ProductSpecification(label: 'Rows', value: '2'),
    ],
    compatibility: const ['Apache RTR 160', 'Apache RTR 200'],
    popularity: 40,
    ageDays: 45,
    featured: true,
    reviews: [
      _rv('rv-rad-1', 'Anil', 5, 'Engine temps dropped noticeably.', '1 week ago', helpful: 8),
    ],
  ),
  _p(
    'p-fuel-cap',
    'Fuel Tank Cap',
    'hero',
    'Hero',
    'engine-parts',
    349,
    449,
    rating: 4.0,
    ratingCount: 150,
    image: 'assets/fuel tank cap.png',
    description: 'Genuine-style fuel tank cap with lock, vented and weather sealed.',
    specifications: const [
      ProductSpecification(label: 'Type', value: 'Lockable'),
      ProductSpecification(label: 'Material', value: 'Chrome Plated Steel'),
    ],
    popularity: 35,
    ageDays: 70,
  ),

  // ── Brake System ─────────────────────────────────────────────────────
  _p(
    'p-brake-pads',
    'Ceramic Brake Pads',
    'bosch',
    'Bosch',
    'brake-system',
    699,
    999,
    rating: 4.7,
    ratingCount: 1240,
    image: 'assets/break pads.png',
    description:
        'Bosch ceramic front brake pads with low dust, low noise and consistent stopping power.',
    specifications: const [
      ProductSpecification(label: 'Material', value: 'Ceramic'),
      ProductSpecification(label: 'Position', value: 'Front'),
      ProductSpecification(label: 'Noise', value: 'Low'),
    ],
    compatibility: const ['Activa 6G', 'Pulsar 150', 'Honda City'],
    popularity: 98,
    ageDays: 5,
    bestSeller: true,
    flashDeal: true,
    reviews: [
      _rv('rv-brake-1', 'Mahesh', 5, 'Incredible bite, zero noise. Highly recommended.', '1 week ago', helpful: 34, photos: ['assets/break pads.png']),
      _rv('rv-brake-2', 'Divya', 4, 'Good pads, standard install.', '2 weeks ago', helpful: 9),
      _rv('rv-brake-3', 'Rahul', 5, 'Braking feels way safer now.', '1 month ago', helpful: 15),
    ],
  ),
  _p(
    'p-brake-shoes',
    'Brake Shoes Set',
    'tvs',
    'TVS',
    'brake-system',
    449,
    599,
    rating: 4.2,
    ratingCount: 320,
    description: 'Quality asbestos-free brake shoe set with even wear and strong bite.',
    specifications: const [
      ProductSpecification(label: 'Position', value: 'Rear'),
      ProductSpecification(label: 'Material', value: 'Asbestos Free'),
      ProductSpecification(label: 'Qty', value: '1 Pair'),
    ],
    popularity: 52,
    ageDays: 28,
    reviews: [
      _rv('rv-shoes-1', 'Ganesh', 4, 'Value for money, works well.', '3 weeks ago', helpful: 5),
    ],
  ),
  _p(
    'p-brake-disc',
    'Front Brake Disc',
    'tvs',
    'TVS',
    'brake-system',
    1299,
    1599,
    rating: 4.3,
    ratingCount: 180,
    description: 'Wave-style floating brake disc for better heat dissipation and looks.',
    specifications: const [
      ProductSpecification(label: 'Diameter', value: '280 mm'),
      ProductSpecification(label: 'Type', value: 'Floating'),
      ProductSpecification(label: 'Material', value: 'Stainless Steel'),
    ],
    popularity: 48,
    ageDays: 40,
    reviews: [
      _rv('rv-disc-1', 'Suresh', 5, 'Looks amazing and stops great.', '2 weeks ago', helpful: 11),
    ],
  ),
  _p(
    'p-brake-fluid',
    'DOT 4 Brake Fluid 500ml',
    'motul',
    'Motul',
    'brake-system',
    449,
    549,
    rating: 4.5,
    ratingCount: 540,
    description: 'High boiling point DOT 4 brake fluid for consistent brake feel in all conditions.',
    specifications: const [
      ProductSpecification(label: 'Volume', value: '500 ml'),
      ProductSpecification(label: 'Spec', value: 'DOT 4'),
      ProductSpecification(label: 'Dry Boiling Point', value: '260°C'),
    ],
    popularity: 66,
    ageDays: 18,
    trending: true,
    reviews: [
      _rv('rv-fluid-1', 'Arjun', 5, 'Bleeding was easy, great fluid.', '1 week ago', helpful: 6),
    ],
  ),

  // ── Oils ─────────────────────────────────────────────────────────────
  _p(
    'p-engine-oil',
    '4T Engine Oil 10W-30 (1L)',
    'castrol',
    'Castrol',
    'oils',
    499,
    649,
    rating: 4.6,
    ratingCount: 2100,
    image: 'assets/engine oil.png',
    description: 'Castrol 4T engine oil for smooth gear shifts and strong engine protection.',
    specifications: const [
      ProductSpecification(label: 'Grade', value: '10W-30'),
      ProductSpecification(label: 'Volume', value: '1 Litre'),
      ProductSpecification(label: 'API', value: 'SL'),
    ],
    compatibility: const ['Activa', 'Access', 'All 4T bikes'],
    popularity: 99,
    ageDays: 3,
    bestSeller: true,
    trending: true,
    flashDeal: true,
    reviews: [
      _rv('rv-oil-1', 'Vinod', 5, 'Smooth engine, great mileage.', '5 days ago', helpful: 41, photos: ['assets/engine oil.png']),
      _rv('rv-oil-2', 'Lakshmi', 4, 'Genuine bottle, sealed properly.', '2 weeks ago', helpful: 7),
      _rv('rv-oil-3', 'Prakash', 5, 'Best oil for daily commuters.', '1 month ago', helpful: 18),
    ],
  ),
  _p(
    'p-synth-oil',
    'Full Synthetic 10W-40 (1L)',
    'motul',
    'Motul',
    'oils',
    799,
    999,
    rating: 4.7,
    ratingCount: 760,
    description: '100% synthetic Motul oil for performance bikes — stable at high temps.',
    specifications: const [
      ProductSpecification(label: 'Grade', value: '10W-40'),
      ProductSpecification(label: 'Volume', value: '1 Litre'),
      ProductSpecification(label: 'API', value: 'SN'),
    ],
    compatibility: const ['All performance bikes'],
    popularity: 88,
    ageDays: 9,
    featured: true,
    trending: true,
    reviews: [
      _rv('rv-synth-1', 'Fahad', 5, 'Engine feels smoother and quieter.', '1 week ago', helpful: 22),
    ],
  ),
  _p(
    'p-chain-lube',
    'Chain Cleaner & Lube Kit',
    'motul',
    'Motul',
    'oils',
    549,
    699,
    rating: 4.4,
    ratingCount: 410,
    description: 'Cleaner + chain lube kit to keep your chain running long and rust-free.',
    specifications: const [
      ProductSpecification(label: 'Contents', value: 'Cleaner + Lube'),
      ProductSpecification(label: 'Volume', value: '2 x 400 ml'),
    ],
    popularity: 61,
    ageDays: 22,
    trending: true,
    reviews: [
      _rv('rv-lube-1', 'Naveen', 4, 'Great combo, works well.', '2 weeks ago', helpful: 4),
    ],
  ),
  _p(
    'p-coolant',
    'Coolant Concentrate 1L',
    'castrol',
    'Castrol',
    'oils',
    349,
    449,
    rating: 4.2,
    ratingCount: 290,
    description: 'Ready-to-mix coolant concentrate with anti-corrosion protection.',
    specifications: const [
      ProductSpecification(label: 'Volume', value: '1 Litre'),
      ProductSpecification(label: 'Colour', value: 'Red'),
    ],
    popularity: 38,
    ageDays: 50,
    reviews: [
      _rv('rv-coolant-1', 'Joseph', 4, 'Good coolant, mixes easily.', '1 month ago', helpful: 3),
    ],
  ),

  // ── Tyres ────────────────────────────────────────────────────────────
  _p(
    'p-bike-tyre',
    'MRF Zapper Tubeless Tyre',
    'mrf',
    'MRF',
    'tyres',
    1599,
    1999,
    rating: 4.5,
    ratingCount: 980,
    image: 'assets/bike tyre.jpg',
    description: 'MRF Zapper sporty tubeless tyre with excellent grip on wet and dry roads.',
    specifications: const [
      ProductSpecification(label: 'Size', value: '90/90-17'),
      ProductSpecification(label: 'Type', value: 'Tubeless'),
      ProductSpecification(label: 'Load Index', value: '49'),
    ],
    compatibility: const ['Pulsar', 'FZ', 'Apache', 'R15'],
    popularity: 90,
    ageDays: 6,
    bestSeller: true,
    flashDeal: true,
    reviews: [
      _rv('rv-tyre-1', 'Deepak', 5, 'Great grip in rain, worth every rupee.', '1 week ago', helpful: 27, photos: ['assets/bike tyre.jpg']),
      _rv('rv-tyre-2', 'Meera', 4, 'Good tyre, fits my FZ perfectly.', '3 weeks ago', helpful: 6),
    ],
  ),
  _p(
    'p-scooter-tyre',
    'Scooter Tubeless Tyre',
    'ceat',
    'CEAT',
    'tyres',
    1299,
    1599,
    rating: 4.1,
    ratingCount: 470,
    description: 'Durable scooter tyre with reinforced sidewall for pothole-heavy roads.',
    specifications: const [
      ProductSpecification(label: 'Size', value: '90/100-10'),
      ProductSpecification(label: 'Type', value: 'Tubeless'),
    ],
    compatibility: const ['Activa', 'Access', 'Jupiter'],
    popularity: 54,
    ageDays: 30,
    reviews: [
      _rv('rv-ctyre-1', 'Srinivas', 4, 'Solid tyre for daily rides.', '2 weeks ago', helpful: 5),
    ],
  ),
  _p(
    'p-car-tyre',
    'Car Tyre 175/65 R14',
    'mrf',
    'MRF',
    'tyres',
    3499,
    4299,
    rating: 4.4,
    ratingCount: 330,
    description: 'MRF car radial tyre — quiet, comfortable and long lasting.',
    specifications: const [
      ProductSpecification(label: 'Size', value: '175/65 R14'),
      ProductSpecification(label: 'Type', value: 'Radial'),
    ],
    compatibility: const ['Wagon R', 'Celerio', 'Swift', 'i10'],
    vehicles: const [VehicleType.car],
    popularity: 70,
    ageDays: 15,
    featured: true,
    reviews: [
      _rv('rv-ctyre2-1', 'Harish', 5, 'Quiet ride, great on highways.', '1 week ago', helpful: 14),
    ],
  ),

  // ── Batteries ─────────────────────────────────────────────────────────
  _p(
    'p-battery',
    'Exide 12V 35Ah Battery',
    'exide',
    'Exide',
    'batteries',
    3499,
    4499,
    rating: 4.6,
    ratingCount: 620,
    image: 'assets/battery.png',
    description: 'Maintenance-free Exide battery with long service life and strong cranking power.',
    specifications: const [
      ProductSpecification(label: 'Voltage', value: '12V'),
      ProductSpecification(label: 'Capacity', value: '35 Ah'),
      ProductSpecification(label: 'Type', value: 'Maintenance Free'),
    ],
    compatibility: const ['Honda City', 'Swift', 'Creta'],
    vehicles: const [VehicleType.car, VehicleType.suv],
    popularity: 85,
    ageDays: 10,
    featured: true,
    bestSeller: true,
    flashDeal: true,
    reviews: [
      _rv('rv-batt-1', 'Ramesh', 5, 'Battery delivered and fitted, no issues.', '2 weeks ago', helpful: 19, photos: ['assets/battery.png']),
      _rv('rv-batt-2', 'Kavya', 4, 'Good battery, competitive price.', '1 month ago', helpful: 8),
    ],
  ),
  _p(
    'p-battery-amaron',
    'Amaron 5Amp Battery',
    'amaron',
    'Amaron',
    'batteries',
    3299,
    3999,
    rating: 4.5,
    ratingCount: 510,
    description: 'Amaron hi-life battery with extra power for accessories and accessories.',
    specifications: const [
      ProductSpecification(label: 'Voltage', value: '12V'),
      ProductSpecification(label: 'Capacity', value: '5 Amp'),
      ProductSpecification(label: 'Warranty', value: '30 months'),
    ],
    compatibility: const ['Pulsar', 'Apache', 'Passion'],
    popularity: 72,
    ageDays: 17,
    reviews: [
      _rv('rv-amaron-1', 'Vijay', 5, 'Cranking power is excellent.', '1 week ago', helpful: 10),
    ],
  ),
  _p(
    'p-battery-charger',
    'Smart Battery Charger',
    'bosch',
    'Bosch',
    'batteries',
    1799,
    2199,
    rating: 4.3,
    ratingCount: 260,
    description: 'Smart 6A charger with auto cut-off and reverse polarity protection.',
    specifications: const [
      ProductSpecification(label: 'Output', value: '6A'),
      ProductSpecification(label: 'Input', value: '100-240V'),
      ProductSpecification(label: 'Protection', value: 'Polarity + Overcharge'),
    ],
    popularity: 44,
    ageDays: 55,
    reviews: [
      _rv('rv-charger-1', 'Anand', 5, 'Auto cut-off works perfectly.', '3 weeks ago', helpful: 7),
    ],
  ),

  // ── Accessories ───────────────────────────────────────────────────────
  _p(
    'p-gear-knob',
    'Racing Gear Knob',
    '3m',
    '3M',
    'accessories',
    499,
    699,
    rating: 4.0,
    ratingCount: 190,
    image: 'assets/gear knob.png',
    description: 'Aluminium racing gear knob with carbon finish and snug fit.',
    specifications: const [
      ProductSpecification(label: 'Material', value: 'Aluminium'),
      ProductSpecification(label: 'Finish', value: 'Carbon'),
    ],
    popularity: 36,
    ageDays: 48,
    reviews: [
      _rv('rv-knob-1', 'Teja', 4, 'Feels great in hand.', '2 weeks ago', helpful: 2),
    ],
  ),
  _p(
    'p-helmet-lock',
    'Helmet Lock',
    'hero',
    'Hero',
    'accessories',
    249,
    349,
    rating: 4.2,
    ratingCount: 400,
    image: 'assets/helmet lock.png',
    description: 'Sturdy helmet lock with key, mounts under the seat.',
    specifications: const [
      ProductSpecification(label: 'Type', value: 'Key Lock'),
      ProductSpecification(label: 'Material', value: 'Zinc Alloy'),
    ],
    popularity: 58,
    ageDays: 20,
    reviews: [
      _rv('rv-hlock-1', 'Sunil', 4, 'Simple and effective.', '1 week ago', helpful: 5),
    ],
  ),
  _p(
    'p-tool-kit',
    '27pc Tool Kit',
    'bosch',
    'Bosch',
    'accessories',
    999,
    1399,
    rating: 4.5,
    ratingCount: 530,
    image: 'assets/tool kit.png',
    description: 'Complete 27-piece tool kit with bag — everything for roadside fixes.',
    specifications: const [
      ProductSpecification(label: 'Pieces', value: '27'),
      ProductSpecification(label: 'Carry Case', value: 'Yes'),
    ],
    popularity: 63,
    ageDays: 25,
    reviews: [
      _rv('rv-tools-1', 'Manikanta', 5, 'Every tool you need, great quality.', '2 weeks ago', helpful: 16),
    ],
  ),
  _p(
    'p-car-jack',
    'Hydraulic Car Jack 2T',
    'bosch',
    'Bosch',
    'accessories',
    1499,
    1899,
    rating: 4.4,
    ratingCount: 380,
    image: 'assets/car jack.png',
    description: '2-tonne hydraulic trolley jack for safe and easy tyre changes.',
    specifications: const [
      ProductSpecification(label: 'Capacity', value: '2 Tonne'),
      ProductSpecification(label: 'Type', value: 'Trolley Jack'),
    ],
    vehicles: const [VehicleType.car, VehicleType.suv],
    popularity: 55,
    ageDays: 33,
    reviews: [
      _rv('rv-jack-1', 'Pranav', 5, 'Lifts my SUV effortlessly.', '1 week ago', helpful: 9),
    ],
  ),
  _p(
    'p-side-mirror',
    'Chrome Side Mirror',
    'hero',
    'Hero',
    'accessories',
    549,
    699,
    rating: 4.1,
    ratingCount: 230,
    image: 'assets/side_mirror.png',
    description: 'Classic chrome side mirror with clear optics and easy adjustment.',
    specifications: const [
      ProductSpecification(label: 'Finish', value: 'Chrome'),
      ProductSpecification(label: 'Glass', value: 'Non-distortion'),
    ],
    popularity: 42,
    ageDays: 44,
    reviews: [
      _rv('rv-mirror-1', 'Dinesh', 4, 'Good mirror, matches the bike.', '3 weeks ago', helpful: 4),
    ],
  ),

  // ── Cleaning ──────────────────────────────────────────────────────────
  _p(
    'p-shampoo',
    'Car Shampoo 1L',
    '3m',
    '3M',
    'cleaning',
    399,
    499,
    rating: 4.4,
    ratingCount: 440,
    description: 'pH balanced 3M car shampoo that foams rich and is paint safe.',
    specifications: const [
      ProductSpecification(label: 'Volume', value: '1 Litre'),
      ProductSpecification(label: 'pH', value: 'Balanced (7)'),
    ],
    popularity: 50,
    ageDays: 27,
    reviews: [
      _rv('rv-shampoo-1', 'Sai', 5, 'Rich foam, great shine.', '1 week ago', helpful: 12),
    ],
  ),
  _p(
    'p-wax',
    'Carnauba Wax Paste',
    '3m',
    '3M',
    'cleaning',
    649,
    799,
    rating: 4.5,
    ratingCount: 310,
    description: 'Deep gloss carnauba wax paste with long-lasting protection.',
    specifications: const [
      ProductSpecification(label: 'Weight', value: '250 g'),
      ProductSpecification(label: 'Finish', value: 'Deep Gloss'),
    ],
    popularity: 47,
    ageDays: 38,
    reviews: [
      _rv('rv-wax-1', 'Rohit', 5, 'Incredible shine, lasts weeks.', '2 weeks ago', helpful: 8),
    ],
  ),
  _p(
    'p-microfiber',
    'Microfiber Cloth Pack',
    '3m',
    '3M',
    'cleaning',
    199,
    299,
    rating: 4.3,
    ratingCount: 620,
    description: 'Pack of 3 lint-free microfiber cloths for streak-free cleaning.',
    specifications: const [
      ProductSpecification(label: 'Qty', value: '3'),
      ProductSpecification(label: 'Size', value: '40 x 40 cm'),
    ],
    popularity: 68,
    ageDays: 14,
    reviews: [
      _rv('rv-mf-1', 'Girish', 5, 'No scratches, absorbs great.', '5 days ago', helpful: 20),
    ],
  ),

  // ── Lights ────────────────────────────────────────────────────────────
  _p(
    'p-headlight',
    'LED Headlight 7"',
    'philips',
    'Philips',
    'lights',
    899,
    1199,
    rating: 4.4,
    ratingCount: 350,
    description: 'Philips LED headlight with crisp white light and plug-and-play fit.',
    specifications: const [
      ProductSpecification(label: 'Size', value: '7 Inch'),
      ProductSpecification(label: 'Beam', value: 'Low + High'),
      ProductSpecification(label: 'Power', value: '36W'),
    ],
    popularity: 57,
    ageDays: 19,
    featured: true,
    reviews: [
      _rv('rv-head-1', 'Shankar', 5, 'Night visibility is amazing.', '1 week ago', helpful: 18),
    ],
  ),
  _p(
    'p-fog-light',
    'Fog Lamp Kit',
    'hella',
    'Hella',
    'lights',
    1299,
    1599,
    rating: 4.3,
    ratingCount: 210,
    description: 'Hella fog lamp kit with switch and relay — safe driving in fog.',
    specifications: const [
      ProductSpecification(label: 'Type', value: 'Halogen'),
      ProductSpecification(label: 'Includes', value: 'Switch + Relay'),
    ],
    vehicles: const [VehicleType.car, VehicleType.suv],
    popularity: 46,
    ageDays: 29,
    trending: true,
    reviews: [
      _rv('rv-fog-1', 'Kiran', 4, 'Bright and easy to install.', '2 weeks ago', helpful: 6),
    ],
  ),
  _p(
    'p-tail-light',
    'LED Tail Light',
    'osram',
    'Osram',
    'lights',
    749,
    999,
    rating: 4.2,
    ratingCount: 280,
    description: 'Osram LED tail light with smoked lens and brake light function.',
    specifications: const [
      ProductSpecification(label: 'Type', value: 'LED'),
      ProductSpecification(label: 'Lens', value: 'Smoked'),
    ],
    popularity: 39,
    ageDays: 42,
    reviews: [
      _rv('rv-tail-1', 'Farhan', 4, 'Looks sharp, bright brake light.', '3 weeks ago', helpful: 3),
    ],
  ),

  // ── Filters ───────────────────────────────────────────────────────────
  _p(
    'p-air-filter',
    'Air Filter',
    'bosch',
    'Bosch',
    'filters',
    449,
    599,
    rating: 4.5,
    ratingCount: 700,
    description: 'Bosch air filter with multi-layer media for maximum airflow and filtration.',
    specifications: const [
      ProductSpecification(label: 'Type', value: 'Paper Element'),
      ProductSpecification(label: 'Replaces', value: 'OE Standard'),
    ],
    compatibility: const ['Activa', 'Pulsar', 'Splendor'],
    popularity: 76,
    ageDays: 11,
    bestSeller: true,
    reviews: [
      _rv('rv-air-1', 'Charan', 5, 'Better pickup after replacing.', '1 week ago', helpful: 13),
    ],
  ),
  _p(
    'p-oil-filter',
    'Oil Filter',
    'bosch',
    'Bosch',
    'filters',
    299,
    399,
    rating: 4.3,
    ratingCount: 540,
    description: 'Bosch oil filter cartridge with high filtration efficiency.',
    specifications: const [
      ProductSpecification(label: 'Type', value: 'Cartridge'),
      ProductSpecification(label: 'Thread', value: '20 x 1.5'),
    ],
    popularity: 60,
    ageDays: 23,
    reviews: [
      _rv('rv-of-1', 'Bharath', 4, 'Genuine quality filter.', '2 weeks ago', helpful: 5),
    ],
  ),
  _p(
    'p-fuel-filter',
    'Fuel Filter',
    'tvs',
    'TVS',
    'filters',
    349,
    449,
    rating: 4.1,
    ratingCount: 320,
    description: 'In-line fuel filter that keeps injectors and carburettors clean.',
    specifications: const [
      ProductSpecification(label: 'Type', value: 'In-line'),
      ProductSpecification(label: 'Fits', value: 'Most bikes & scooters'),
    ],
    popularity: 33,
    ageDays: 66,
    reviews: [
      _rv('rv-ff-1', 'Nithin', 4, 'Easy fit, clean fuel flow.', '1 month ago', helpful: 4),
    ],
  ),

  // ── Electronics ───────────────────────────────────────────────────────
  _p(
    'p-dashcam',
    '1080p Dash Camera',
    'hella',
    'Hella',
    'electronics',
    3499,
    4499,
    rating: 4.4,
    ratingCount: 190,
    image: 'assets/Dashboard Camera.png',
    description: 'Full HD 1080p dash camera with night vision and loop recording.',
    specifications: const [
      ProductSpecification(label: 'Resolution', value: '1080p'),
      ProductSpecification(label: 'Night Vision', value: 'Yes'),
      ProductSpecification(label: 'Loop', value: 'Yes'),
    ],
    vehicles: const [VehicleType.car, VehicleType.suv],
    popularity: 74,
    ageDays: 7,
    featured: true,
    trending: true,
    flashDeal: true,
    reviews: [
      _rv('rv-dash-1', 'Vamsi', 5, 'Crystal clear footage, great buy.', '1 week ago', helpful: 17, photos: ['assets/Dashboard Camera.png']),
      _rv('rv-dash-2', 'Rani', 4, 'Easy to install, app works fine.', '3 weeks ago', helpful: 6),
    ],
  ),
  _p(
    'p-gps',
    'GPS Vehicle Tracker',
    'hella',
    'Hella',
    'electronics',
    2499,
    2999,
    rating: 4.2,
    ratingCount: 160,
    image: 'assets/gps tracker.png',
    description: 'Real-time GPS tracker with anti-theft alerts and mobile app.',
    specifications: const [
      ProductSpecification(label: 'Network', value: '2G/4G'),
      ProductSpecification(label: 'Alerts', value: 'Geo-fence + SOS'),
    ],
    popularity: 53,
    ageDays: 13,
    trending: true,
    reviews: [
      _rv('rv-gps-1', 'Abdul', 5, 'Very accurate tracking, great peace of mind.', '1 week ago', helpful: 11),
    ],
  ),
  _p(
    'p-tyre-sensor',
    'TPMS Kit',
    'bosch',
    'Bosch',
    'electronics',
    1899,
    2499,
    rating: 4.3,
    ratingCount: 140,
    description: 'Tyre pressure monitoring system with live dashboard display.',
    specifications: const [
      ProductSpecification(label: 'Sensors', value: '4 External'),
      ProductSpecification(label: 'Display', value: 'Solar / USB'),
    ],
    vehicles: const [VehicleType.car, VehicleType.suv],
    popularity: 41,
    ageDays: 36,
    reviews: [
      _rv('rv-tpms-1', 'Yash', 4, 'Works great, screen is clear.', '2 weeks ago', helpful: 7),
    ],
  ),
  _p(
    'p-out-of-stock',
    'OBD2 Diagnostic Scanner',
    'bosch',
    'Bosch',
    'electronics',
    3999,
    4999,
    rating: 4.5,
    ratingCount: 90,
    stock: 0,
    description: 'Bluetooth OBD2 scanner that reads and clears engine fault codes.',
    specifications: const [
      ProductSpecification(label: 'Interface', value: 'Bluetooth'),
      ProductSpecification(label: 'Protocols', value: 'OBD2'),
    ],
    vehicles: const [VehicleType.car, VehicleType.suv],
    popularity: 30,
    ageDays: 4,
    reviews: [
      _rv('rv-obd-1', 'Ravi Teja', 5, 'Saves trips to the garage!', '1 week ago', helpful: 9),
    ],
  ),
];
