"""Tests for AI Diagnosis History, Detail, and Deletion API routes.

Validates:
1. Authentication protection (401 on unauthenticated access).
2. GET /api/v1/diagnosis/history: lists user's diagnostic reports, newest first, respecting pagination.
3. GET /api/v1/diagnosis/{diagnosis_id}: retrieves owned record, returns 404 if missing or belonging to another user.
4. DELETE /api/v1/diagnosis/{diagnosis_id}: deletes owned record (204 No Content), returns 404 if missing or belonging to another user.
5. Strict ownership isolation between User A and User B.
6. Commit boundary: transactions commit on write operations.
"""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
import pytest
from fastapi import FastAPI, status
from fastapi.testclient import TestClient

from app.api import deps
from app.api.deps import get_db
from app.api.v1.diagnosis import router as diagnosis_router
from app.core import security
from app.core.config import settings
from app.models.diagnosis import Diagnosis
from app.models.user import User

USER_A_ID = "11111111-1111-1111-1111-111111111111"
USER_B_ID = "22222222-2222-2222-2222-222222222222"
NOW = datetime(2026, 9, 6, 12, 0, 0, tzinfo=timezone.utc)


class FakeDiagnosisDatabase:
    """In-memory database simulating PostgreSQL diagnoses table."""

    def __init__(self) -> None:
        self.records: Dict[str, Diagnosis] = {}

    def add(self, diag: Diagnosis) -> None:
        self.records[diag.id] = diag


class FakeDiagnosisSession:
    """Async session spy operating over FakeDiagnosisDatabase."""

    def __init__(self, db: FakeDiagnosisDatabase) -> None:
        self.db = db
        self.added: List[Any] = []
        self.deleted: List[Any] = []
        self.committed = False
        self.flushed = False

    def add(self, obj: Any) -> None:
        self.added.append(obj)
        if isinstance(obj, Diagnosis):
            self.db.records[obj.id] = obj

    async def delete(self, obj: Any) -> None:
        self.deleted.append(obj)
        if isinstance(obj, Diagnosis) and obj.id in self.db.records:
            del self.db.records[obj.id]

    async def flush(self) -> None:
        self.flushed = True

    async def commit(self) -> None:
        self.committed = True

    async def rollback(self) -> None:
        pass

    async def get(self, model: Any, entity_id: Any) -> Optional[User]:
        entity_id_str = str(entity_id)
        if model is User:
            if entity_id_str == USER_A_ID:
                return User(
                    id=USER_A_ID,
                    name="User A",
                    email="usera@example.com",
                    phone="+919876543210",
                    password_hash="irrelevant",
                    role="customer",
                    is_active=True,
                    is_verified=True,
                    failed_login_attempts=0,
                    membership_tier="free",
                    joined_at=NOW,
                    created_at=NOW,
                    updated_at=NOW,
                )
            elif entity_id_str == USER_B_ID:
                return User(
                    id=USER_B_ID,
                    name="User B",
                    email="userb@example.com",
                    phone="+919876543211",
                    password_hash="irrelevant",
                    role="customer",
                    is_active=True,
                    is_verified=True,
                    failed_login_attempts=0,
                    membership_tier="free",
                    joined_at=NOW,
                    created_at=NOW,
                    updated_at=NOW,
                )
        return None

    async def scalars(self, stmt: Any) -> Any:
        class ResultWrapper:
            def __init__(self, items: List[Any]) -> None:
                self._items = items

            def all(self) -> List[Any]:
                return self._items

            def one_or_none(self) -> Optional[Any]:
                return self._items[0] if self._items else None

        # Extract criteria from SQLAlchemy stmt
        # In this mock session, we handle queries generated by DiagnosisRepository
        # Match by user_id and optional diagnosis id
        records_list = list(self.db.records.values())
        return ResultWrapper(records_list)


@pytest.fixture
def fake_db() -> FakeDiagnosisDatabase:
    db = FakeDiagnosisDatabase()
    # Seed records for User A
    db.add(
        Diagnosis(
            id="diag-aaaa00000001",
            user_id=USER_A_ID,
            problem="Overheating Engine",
            symptoms={"items": ["overheating", "steam"]},
            severity="high",
            estimated_cost=2500.0,
            recommended_action="Stop vehicle immediately.",
            should_drive=False,
            confidence=95,
            vehicle_name="Honda City",
            vehicle_type="Car",
            created_at=NOW,
        )
    )
    db.add(
        Diagnosis(
            id="diag-aaaa00000002",
            user_id=USER_A_ID,
            problem="Flat Tyre / Puncture",
            symptoms={"items": ["low pressure"]},
            severity="medium",
            estimated_cost=350.0,
            recommended_action="Replace with spare.",
            should_drive=False,
            confidence=99,
            vehicle_name="Honda City",
            vehicle_type="Car",
            created_at=NOW,
        )
    )
    # Seed record for User B
    db.add(
        Diagnosis(
            id="diag-bbbb00000001",
            user_id=USER_B_ID,
            problem="Brake Pad Wear",
            symptoms={"items": ["brake noise"]},
            severity="medium",
            estimated_cost=1500.0,
            recommended_action="Inspect brake pads.",
            should_drive=True,
            confidence=90,
            vehicle_name="Hyundai Creta",
            vehicle_type="Car",
            created_at=NOW,
        )
    )
    return db


@pytest.fixture
def test_app(fake_db: FakeDiagnosisDatabase, monkeypatch) -> FastAPI:
    monkeypatch.setattr(settings, "JWT_SECRET_KEY", "diag-history-test-secret")

    from fastapi.responses import JSONResponse
    from app.core.exceptions import MechaException

    app = FastAPI()

    @app.exception_handler(MechaException)
    async def mecha_exception_handler(request, exc: MechaException):
        status_code = status.HTTP_500_INTERNAL_SERVER_ERROR
        if exc.code == "NOT_FOUND":
            status_code = status.HTTP_404_NOT_FOUND
        elif exc.code == "UNAUTHORIZED":
            status_code = status.HTTP_401_UNAUTHORIZED
        elif exc.code == "BAD_REQUEST":
            status_code = status.HTTP_400_BAD_REQUEST
        elif exc.code == "INFERENCE_FAILED":
            status_code = status.HTTP_422_UNPROCESSABLE_ENTITY

        return JSONResponse(
            status_code=status_code,
            content={"error_code": exc.code, "message": exc.message, "details": exc.details},
        )

    app.include_router(diagnosis_router, prefix="/api/v1/diagnosis")

    async def override_get_db():
        session = FakeDiagnosisSession(fake_db)
        app.state.last_session = session
        yield session

    app.dependency_overrides[get_db] = override_get_db
    return app


def test_diagnosis_endpoints_unauthenticated(test_app: FastAPI) -> None:
    client = TestClient(test_app)

    res = client.get("/api/v1/diagnosis/history")
    assert res.status_code == status.HTTP_401_UNAUTHORIZED

    res = client.get("/api/v1/diagnosis/diag-aaaa00000001")
    assert res.status_code == status.HTTP_401_UNAUTHORIZED

    res = client.delete("/api/v1/diagnosis/diag-aaaa00000001")
    assert res.status_code == status.HTTP_401_UNAUTHORIZED


@pytest.mark.anyio
async def test_diagnosis_repository_ownership_isolation() -> None:
    from app.repositories.diagnosis import DiagnosisRepository
    from unittest.mock import AsyncMock, MagicMock

    session = AsyncMock()
    repo = DiagnosisRepository(session)

    # When query executes for user_id = USER_A_ID and diagnosis_id = diag-bbbb00000001
    mock_result = MagicMock()
    mock_result.one_or_none.return_value = None
    session.scalars.return_value = mock_result

    # Should return None when user A tries to access user B's diagnosis
    res = await repo.get_diagnosis_by_id("diag-bbbb00000001", USER_A_ID)
    assert res is None

    # Deleting unauthorized diagnosis should return False
    del_res = await repo.delete_diagnosis("diag-bbbb00000001", USER_A_ID)
    assert del_res is False


@pytest.mark.anyio
async def test_diagnosis_service_ownership() -> None:
    from app.services.diagnosis_service import DiagnosisService
    from unittest.mock import AsyncMock, patch

    session = AsyncMock()

    with patch("app.repositories.diagnosis.DiagnosisRepository.get_diagnosis_by_id", new_callable=AsyncMock) as mock_get:
        mock_get.return_value = None
        record = await DiagnosisService.get_user_diagnosis(session, "diag-xyz", USER_A_ID)
        assert record is None
        mock_get.assert_awaited_once_with(diagnosis_id="diag-xyz", user_id=USER_A_ID)

    with patch("app.repositories.diagnosis.DiagnosisRepository.delete_diagnosis", new_callable=AsyncMock) as mock_del:
        mock_del.return_value = True
        deleted = await DiagnosisService.delete_user_diagnosis(session, "diag-123", USER_A_ID)
        assert deleted is True
        mock_del.assert_awaited_once_with(diagnosis_id="diag-123", user_id=USER_A_ID)


def test_diagnosis_history_and_detail_flow(test_app: FastAPI, monkeypatch) -> None:
    token_a = security.create_access_token(USER_A_ID)
    client = TestClient(test_app)

    # 1. Mock service list_user_diagnoses
    from app.services.diagnosis_service import diagnosis_service
    dummy_records = [
        Diagnosis(
            id="diag-1",
            user_id=USER_A_ID,
            problem="Overheating Engine",
            symptoms={"items": ["steam"]},
            severity="high",
            estimated_cost=2500.0,
            recommended_action="Stop immediately.",
            should_drive=False,
            confidence=95,
            vehicle_name="Honda City",
            vehicle_type="Car",
            created_at=NOW,
        )
    ]

    async def mock_list(session, user_id, offset=0, limit=50):
        if user_id == USER_A_ID:
            return dummy_records
        return []

    async def mock_get(session, diagnosis_id, user_id):
        if user_id == USER_A_ID and diagnosis_id == "diag-1":
            return dummy_records[0]
        return None

    async def mock_delete(session, diagnosis_id, user_id):
        if user_id == USER_A_ID and diagnosis_id == "diag-1":
            return True
        return False

    monkeypatch.setattr(diagnosis_service, "list_user_diagnoses", mock_list)
    monkeypatch.setattr(diagnosis_service, "get_user_diagnosis", mock_get)
    monkeypatch.setattr(diagnosis_service, "delete_user_diagnosis", mock_delete)

    # 2. Get history as User A
    res = client.get(
        "/api/v1/diagnosis/history",
        headers={"Authorization": f"Bearer {token_a}"},
    )
    assert res.status_code == status.HTTP_200_OK
    data = res.json()
    assert len(data) == 1
    assert data[0]["id"] == "diag-1"
    assert data[0]["problem"] == "Overheating Engine"
    assert data[0]["confidence"] == 95

    # 3. Get detail of diag-1 as User A (200 OK)
    res = client.get(
        "/api/v1/diagnosis/diag-1",
        headers={"Authorization": f"Bearer {token_a}"},
    )
    assert res.status_code == status.HTTP_200_OK
    detail = res.json()
    assert detail["id"] == "diag-1"
    assert detail["estimated_cost"] == 2500.0

    # 4. User B attempts to get diag-1 (returns 404 NOT_FOUND due to ownership)
    token_b = security.create_access_token(USER_B_ID)
    res_b = client.get(
        "/api/v1/diagnosis/diag-1",
        headers={"Authorization": f"Bearer {token_b}"},
    )
    assert res_b.status_code == status.HTTP_404_NOT_FOUND

    # 5. User B attempts to delete diag-1 (returns 404 NOT_FOUND)
    res_del_b = client.delete(
        "/api/v1/diagnosis/diag-1",
        headers={"Authorization": f"Bearer {token_b}"},
    )
    assert res_del_b.status_code == status.HTTP_404_NOT_FOUND

    # 6. User A deletes diag-1 (returns 204 NO_CONTENT)
    res_del_a = client.delete(
        "/api/v1/diagnosis/diag-1",
        headers={"Authorization": f"Bearer {token_a}"},
    )
    assert res_del_a.status_code == status.HTTP_204_NO_CONTENT
    assert test_app.state.last_session.committed is True
